In [16]:
import pandas as pd

In [17]:
!head -n 18 /Users/msolomon/Data/schizophrenia/daner_combined_refmt_no_header.tsv

##Meta_file_format_version	0.99
##Analytic_pipeline	RICOPILI
##Analytic_pipeline_version	2017_3_1
##Comment	limited, only people who have signed 23andMe DTA
##Title	PGC primary MDD analysis
##Date	31 Jan 2017 13:26 CET
##Analyst
##Contact	Mark Daly, MGH
##Genome build	GRCh37/hg19
##Imputation reference	1000 Genomes Project, phase 3
##chromosomes	1-22 X Y XY
##Case_def	SCZ
##Control_def	no SCZ, no BIP
##Diagnosis_def	includes register and self-report data
##number of cohorts	5
##Study cohort IDs
##POP1_def	East Asian
#CHR	BP	REF	ALT	nStudy	Study	P	SCZ_AF	HC_AF	OR	SE	INFO	Qp	I2	MHT.P	Comment

In [94]:
df = pd.read_csv('/Users/msolomon/Data/schizophrenia/daner_combined_refmt.vcf', skiprows=17, delimiter='\t')

In [22]:
len(df)

13698754

In [27]:
df

,#CHR,BP,REF,ALT,nStudy,Study,P,SCZ_AF,HC_AF,OR,SE,INFO,Qp,I2,MHT.P,Comment
0,8,105231413,T,C,2,+?,0.784300,0.95900,0.96000,1.01217,0.0442,0.999,1.00000,0.0,.,.
1,8,106973048,A,G,2,+-,0.424000,0.07130,0.07430,0.98531,0.0185,0.990,0.19900,-81.9,.,.
2,8,101592213,T,C,2,?-,0.385100,0.07160,0.07500,0.98167,0.0213,0.956,1.00000,0.0,.,.
3,8,102569817,A,G,2,-?,0.673600,0.06570,0.06620,0.98383,0.0387,0.885,1.00000,0.0,.,.
4,8,108690829,T,G,2,++,0.595700,0.49300,0.49400,1.00511,0.0095,0.982,0.96350,0.0,.,.
5,8,108681675,A,C,2,-+,0.626000,0.53700,0.53700,1.00451,0.0092,0.997,0.67900,0.0,.,.
6,8,103044620,T,C,2,+-,0.908800,0.87400,0.87300,0.99840,0.0144,0.949,0.11120,-18.2,.,.
7,8,109712249,A,AT,2,--,0.445500,0.75100,0.75100,0.99193,0.0106,0.998,0.70960,0.0,.,.
8,8,106830201,T,C,2,+?,0.532100,0.01120,0.01010,1.17257,0.2548,0.977,1.00000,0.0,.,.
9,8,105176418,T,TTC,2,-+,0.074260,0.81400,0.80800,1.02235,0.0124,0.993,0.22700,-105.5,.,.
10,8,105947202,A,G,2,-?,0.597200,0.01300,0.01520,0.88728,0.2263,0.924,1.00000,0.0,.,.
11,8,104152280,C,G,2,?-,0.334000,0.16100,0.16500,0.98590,0.0147,0.995,1.00000,0.0,.,.
12,8,108626888,T,G,2,+?,0.267000,0.97600,0.97200,1.29758,0.2347,0.745,1.00000,0.0,.,.
13,8,100479917,T,C,2,--,0.385800,0.76800,0.77200,0.99035,0.0112,1.000,0.63370,0.0,.,.
14,8,103144592,A,C,2,-+,0.800700,0.82700,0.82600,0.99690,0.0125,0.984,0.26570,-142.1,.,.
15,8,108166508,A,T,2,++,0.561400,0.68900,0.68500,1.00582,0.0101,0.996,0.80890,0.0,.,.
16,8,102923589,C,CTTTTTTT,2,?-,0.144400,0.00956,0.00889,1.09057,0.0594,0.974,1.00000,0.0,.,.
17,8,101041131,T,C,2,-?,0.668700,0.11400,0.11600,0.98847,0.0271,1.000,1.00000,0.0,.,.
18,8,105201080,T,C,2,-+,0.020340,0.43400,0.42900,1.02245,0.0096,0.999,0.07809,3.4,.,.
19,8,109964318,A,G,2,?+,0.198100,0.03370,0.03280,1.03977,0.0303,1.000,1.00000,0.0,.,.
20,8,100526345,A,G,2,-?,0.681600,0.98900,0.99000,0.92284,0.1957,0.925,1.00000,0.0,.,.
21,8,101012421,T,C,2,+-,0.935800,0.41400,0.41600,1.00080,0.0093,0.998,0.22650,-105.1,.,.
22,8,103650415,A,G,2,++,0.202600,0.14400,0.14000,1.01694,0.0132,0.996,0.06011,15.1,.,.
23,8,100006266,A,G,2,-?,0.260300,0.98800,0.99000,0.79581,0.2029,0.591,1.00000,0.0,.,.
24,8,105861171,T,TG,2,-?,0.341900,0.98900,0.99100,0.84485,0.1774,0.886,1.00000,0.0,.,.
25,8,109224500,A,G,2,--,0.005407,0.30300,0.30600,0.97200,0.0102,0.998,0.84860,0.0,.,.
26,8,101644243,A,G,2,-+,0.210300,0.14800,0.14900,0.98373,0.0131,0.996,0.04331,26.5,.,.
27,8,106876955,A,G,2,+?,0.771800,0.01160,0.01130,1.07444,0.2476,0.950,1.00000,0.0,.,.
28,8,107978035,T,C,2,++,0.352600,0.35400,0.34800,1.00944,0.0101,0.999,0.98490,0.0,.,.
29,8,105208527,A,G,2,++,0.738400,0.70700,0.70500,1.00341,0.0102,1.000,0.92090,0.0,.,.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13698724,20,41240859,T,G,2,+?,0.686000,0.98400,0.98400,1.03634,0.0883,0.779,1.00000,0.0,.,.
13698725,20,44810434,T,C,2,-+,0.632100,0.65800,0.65200,1.00481,0.0101,0.948,0.22280,-101.9,.,.
13698726,20,40004503,A,G,2,?-,0.862900,0.03300,0.03460,0.99442,0.0324,0.862,1.00000,0.0,.,.
13698727,20,46908388,T,C,2,+?,0.924900,0.01760,0.01760,1.00803,0.0848,0.705,1.00000,0.0,.,.
13698728,20,44361276,T,C,2,-+,0.539600,0.51800,0.51200,1.00592,0.0097,1.010,0.22980,-108.1,.,.
13698729,20,46725953,A,G,2,-?,0.027160,0.98100,0.98300,0.85710,0.0698,0.942,1.00000,0.0,.,.
13698730,20,45255744,T,G,2,++,0.782900,0.61600,0.61200,1.00260,0.0096,0.992,0.78030,0.0,.,.
13698731,20,40657972,A,G,2,?-,0.705300,0.01090,0.01140,0.97971,0.0542,0.958,1.00000,0.0,.,.
13698732,20,47951040,CTTTT,C,2,+-,0.738100,0.74700,0.74700,0.99631,0.0110,0.959,0.67340,0.0,.,.
13698733,20,46641684,A,G,2,-?,0.054190,0.83900,0.84400,0.95466,0.0241,0.972,1.00000,0.0,.,.
13698734,20,48888046,C,G,2,+?,0.036300,0.99300,0.98700,2.67113,0.4693,0.546,1.00000,0.0,.,.
13698735,20,49495288,T,C,2,++,0.166300,0.05850,0.05670,1.03004,0.0213,0.913,0.47370,0.0,.,.
13698736,20,41169938,T,C,2,--,0.031110,0.60600,0.61200,0.97961,0.0095,0.979,0.81270,0.0,.,.
13698737,20,44123367,T,C,2,-+,0.826900,0.98500,0.98600,1.01056,0.0482,0.980,0.31700,-199.6,.,.
13698738,20,49601146,T,C,2,--,0.000034,0.60000,0.61100,0.96098,0.0096,0.973,0.16130,-52.9,.,.
13698739,20,44758629,A,G,2,+?,0.267400,0.01160,0.00850,1.39571,0.3006,0.966,1.00000,0.0,.,.
13698740,20,45762795,T,G,2,--,0.018080,0.37200,0.37800,0.97785,0.0095,0.994,0.38440,0.0,.,.
13698741,20,45214921,T,C,2,--,0.124800,0.09210,0.09530,0.97326,0.0177,0.751,0.01293,51.4,.,.
13698742,20,41802141,T,C,2,?+,0.336700,0.97200,0.97100,1.03231,0.0331,0.969,1.00000,0.0,.,.
13698743,20,41012264,A,G,2,--,0.512200,0.58200,0.58500,0.99372,0.0097,0.998,0.99250,0.0,.,.
13698744,20,45561693,A,G,2,++,0.191500,0.80100,0.80200,1.01623,0.0123,0.992,0.54220,0.0,.,.
13698745,20,44372620,T,C,2,-+,0.449400,0.52000,0.51500,1.00733,0.0097,1.010,0.32810,0.0,.,.
13698746,20,43203203,T,TTTTTTG,2,+-,0.939500,0.05700,0.05660,1.00150,0.0200,0.992,0.26870,-145.3,.,.
13698747,20,49004040,T,C,2,++,0.129700,0.61000,0.61100,1.01481,0.0097,0.987,0.66840,0.0,.,.
13698748,20,40403831,A,G,2,++,0.261900,0.05540,0.05240,1.02327,0.0205,0.996,0.32860,0.0,.,.
13698749,20,47231076,A,G,2,-?,0.183500,0.01540,0.02210,0.63021,0.3471,0.869,1.00000,0.0,.,.
13698750,20,46761380,A,G,2,?+,0.571400,0.01540,0.01520,1.02655,0.0463,0.968,1.00000,0.0,.,.
13698751,20,44168957,T,C,2,+?,0.024420,0.04470,0.04030,1.10285,0.0435,1.000,1.00000,0.0,.,.
13698752,20,45724327,T,C,2,?-,0.498200,0.98600,0.98700,0.96435,0.0536,0.804,1.00000,0.0,.,.
13698753,20,42747689,T,C,2,--,0.512400,0.28100,0.28200,0.99322,0.0104,0.982,0.82960,0.0,.,.

In [29]:
df.groupby(['#CHR']).count()

,BP,REF,ALT,nStudy,Study,P,SCZ_AF,HC_AF,OR,SE,INFO,Qp,I2,MHT.P,Comment
#CHR,,,,,,,,,,,,,,,
1,1074898,1074898,1074898,1074898,1074898,1074898,1074898,1074898,1074898,1074898,1074898,1074898,1074898,1074898,1074898
2,1155015,1155015,1155015,1155015,1155015,1155015,1155015,1155015,1155015,1155015,1155015,1155015,1155015,1155015,1155015
3,971692,971692,971692,971692,971692,971692,971692,971692,971692,971692,971692,971692,971692,971692,971692
4,992960,992960,992960,992960,992960,992960,992960,992960,992960,992960,992960,992960,992960,992960,992960
5,871746,871746,871746,871746,871746,871746,871746,871746,871746,871746,871746,871746,871746,871746,871746
6,922311,922311,922311,922311,922311,922311,922311,922311,922311,922311,922311,922311,922311,922311,922311
7,803756,803756,803756,803756,803756,803756,803756,803756,803756,803756,803756,803756,803756,803756,803756
8,748907,748907,748907,748907,748907,748907,748907,748907,748907,748907,748907,748907,748907,748907,748907
9,595755,595755,595755,595755,595755,595755,595755,595755,595755,595755,595755,595755,595755,595755,595755
10,695401,695401,695401,695401,695401,695401,695401,695401,695401,695401,695401,695401,695401,695401,695401
11,668945,668945,668945,668945,668945,668945,668945,668945,668945,668945,668945,668945,668945,668945,668945
12,666393,666393,666393,666393,666393,666393,666393,666393,666393,666393,666393,666393,666393,666393,666393
13,499271,499271,499271,499271,499271,499271,499271,499271,499271,499271,499271,499271,499271,499271,499271
14,455271,455271,455271,455271,455271,455271,455271,455271,455271,455271,455271,455271,455271,455271,455271
15,402288,402288,402288,402288,402288,402288,402288,402288,402288,402288,402288,402288,402288,402288,402288
16,427219,427219,427219,427219,427219,427219,427219,427219,427219,427219,427219,427219,427219,427219,427219
17,372718,372718,372718,372718,372718,372718,372718,372718,372718,372718,372718,372718,372718,372718,372718
18,384550,384550,384550,384550,384550,384550,384550,384550,384550,384550,384550,384550,384550,384550,384550
19,314678,314678,314678,314678,314678,314678,314678,314678,314678,314678,314678,314678,314678,314678,314678
20,297830,297830,297830,297830,297830,297830,297830,297830,297830,297830,297830,297830,297830,297830,297830
21,184732,184732,184732,184732,184732,184732,184732,184732,184732,184732,184732,184732,184732,184732,184732
22,192418,192418,192418,192418,192418,192418,192418,192418,192418,192418,192418,192418,192418,192418,192418

In [30]:
sub = df[0:10]

In [84]:
def format_variant_id(row):
    row['variant_id'] = '-'.join([str(row['#CHR']), str(row['BP']), str(row['REF']), str(row['ALT'])])
    return row
    
sub.apply(format_variant_id, axis=1)

,#CHR,BP,REF,ALT,nStudy,Study,P,SCZ_AF,HC_AF,OR,SE,INFO,Qp,I2,MHT.P,Comment,variant_id
0,8,105231413,T,C,2,+?,0.78430,0.9590,0.9600,1.01217,0.0442,0.999,1.0000,0.0,.,.,8-105231413-T-C
1,8,106973048,A,G,2,+-,0.42400,0.0713,0.0743,0.98531,0.0185,0.990,0.1990,-81.9,.,.,8-106973048-A-G
2,8,101592213,T,C,2,?-,0.38510,0.0716,0.0750,0.98167,0.0213,0.956,1.0000,0.0,.,.,8-101592213-T-C
3,8,102569817,A,G,2,-?,0.67360,0.0657,0.0662,0.98383,0.0387,0.885,1.0000,0.0,.,.,8-102569817-A-G
4,8,108690829,T,G,2,++,0.59570,0.4930,0.4940,1.00511,0.0095,0.982,0.9635,0.0,.,.,8-108690829-T-G
5,8,108681675,A,C,2,-+,0.62600,0.5370,0.5370,1.00451,0.0092,0.997,0.6790,0.0,.,.,8-108681675-A-C
6,8,103044620,T,C,2,+-,0.90880,0.8740,0.8730,0.99840,0.0144,0.949,0.1112,-18.2,.,.,8-103044620-T-C
7,8,109712249,A,AT,2,--,0.44550,0.7510,0.7510,0.99193,0.0106,0.998,0.7096,0.0,.,.,8-109712249-A-AT
8,8,106830201,T,C,2,+?,0.53210,0.0112,0.0101,1.17257,0.2548,0.977,1.0000,0.0,.,.,8-106830201-T-C
9,8,105176418,T,TTC,2,-+,0.07426,0.8140,0.8080,1.02235,0.0124,0.993,0.2270,-105.5,.,.,8-105176418-T-TTC

In [78]:
CHROMOSOMES = ['chr%s' % x for x in range(1, 23)]
CHROMOSOMES.extend(['chrX', 'chrY', 'chrM'])
CHROMOSOME_TO_CODE = { item: i+1 for i, item in enumerate(CHROMOSOMES) }


def get_single_location(chrom, pos):
    """
    Gets a single location from chromosome and position
    chr must be actual chromosme code (chrY) and pos must be integer

    Borrowed from xbrowse
    """
    return CHROMOSOME_TO_CODE[chrom] * int(1e9) + pos


def get_xpos(chrom, pos):
    """
    Borrowed from xbrowse
    """
    if not chrom.startswith('chr'):
        chrom = 'chr{}'.format(chrom)
    return get_single_location(chrom, int(pos))

def add_xpos_column(row):
    row['xpos'] = get_xpos(str(row['#CHR']), row['BP'])
    return row

sub.apply(add_xpos_column, axis=1)

,#CHR,BP,REF,ALT,nStudy,Study,P,SCZ_AF,HC_AF,OR,SE,INFO,Qp,I2,MHT.P,Comment,variant_id,xpos
0,8,105231413,T,C,2,+?,0.78430,0.9590,0.9600,1.01217,0.0442,0.999,1.0000,0.0,.,.,lol8,8105231413
1,8,106973048,A,G,2,+-,0.42400,0.0713,0.0743,0.98531,0.0185,0.990,0.1990,-81.9,.,.,lol8,8106973048
2,8,101592213,T,C,2,?-,0.38510,0.0716,0.0750,0.98167,0.0213,0.956,1.0000,0.0,.,.,lol8,8101592213
3,8,102569817,A,G,2,-?,0.67360,0.0657,0.0662,0.98383,0.0387,0.885,1.0000,0.0,.,.,lol8,8102569817
4,8,108690829,T,G,2,++,0.59570,0.4930,0.4940,1.00511,0.0095,0.982,0.9635,0.0,.,.,lol8,8108690829
5,8,108681675,A,C,2,-+,0.62600,0.5370,0.5370,1.00451,0.0092,0.997,0.6790,0.0,.,.,lol8,8108681675
6,8,103044620,T,C,2,+-,0.90880,0.8740,0.8730,0.99840,0.0144,0.949,0.1112,-18.2,.,.,lol8,8103044620
7,8,109712249,A,AT,2,--,0.44550,0.7510,0.7510,0.99193,0.0106,0.998,0.7096,0.0,.,.,lol8,8109712249
8,8,106830201,T,C,2,+?,0.53210,0.0112,0.0101,1.17257,0.2548,0.977,1.0000,0.0,.,.,lol8,8106830201
9,8,105176418,T,TTC,2,-+,0.07426,0.8140,0.8080,1.02235,0.0124,0.993,0.2270,-105.5,.,.,lol8,8105176418

In [82]:
def rename_columns(df):
    column_map = {
        '#CHR': 'chr',
        'BP': 'pos',
        'REF': 'ref',
        'ALT': 'alt',
        'nStudy': 'n_study',
        'Study': 'study',
        'P': 'p_value',
        'SCZ_AF': 'scz_af',
        'HC_AF': 'hc_af',
        'OR': 'odds_ratio',
        'SE': 'se',
        'Qp': 'qp',
        'I2': 'i_squared',
        'MHT.P': 'mhtp',
        'Comment': 'comment',
        'INFO': 'info'
    }
    return df.rename(columns=column_map)
rename_columns(sub)

,chr,pos,ref,alt,n_study,study,p_value,scz_af,hc_af,odds_ratio,se,info,qp,i_squared,mhtp,comment,variant_id
0,8,105231413,T,C,2,+?,0.78430,0.9590,0.9600,1.01217,0.0442,0.999,1.0000,0.0,.,.,lol8
1,8,106973048,A,G,2,+-,0.42400,0.0713,0.0743,0.98531,0.0185,0.990,0.1990,-81.9,.,.,lol8
2,8,101592213,T,C,2,?-,0.38510,0.0716,0.0750,0.98167,0.0213,0.956,1.0000,0.0,.,.,lol8
3,8,102569817,A,G,2,-?,0.67360,0.0657,0.0662,0.98383,0.0387,0.885,1.0000,0.0,.,.,lol8
4,8,108690829,T,G,2,++,0.59570,0.4930,0.4940,1.00511,0.0095,0.982,0.9635,0.0,.,.,lol8
5,8,108681675,A,C,2,-+,0.62600,0.5370,0.5370,1.00451,0.0092,0.997,0.6790,0.0,.,.,lol8
6,8,103044620,T,C,2,+-,0.90880,0.8740,0.8730,0.99840,0.0144,0.949,0.1112,-18.2,.,.,lol8
7,8,109712249,A,AT,2,--,0.44550,0.7510,0.7510,0.99193,0.0106,0.998,0.7096,0.0,.,.,lol8
8,8,106830201,T,C,2,+?,0.53210,0.0112,0.0101,1.17257,0.2548,0.977,1.0000,0.0,.,.,lol8
9,8,105176418,T,TTC,2,-+,0.07426,0.8140,0.8080,1.02235,0.0124,0.993,0.2270,-105.5,.,.,lol8

In [106]:
def prepare_data(df):
    #df = df.apply(format_variant_id, axis=1)
    #df = df.apply(add_xpos_column, axis=1)    
    df = rename_columns(df)
    return df
prepared_df = prepare_data(df)

In [131]:
prepared_df.head()

,chr,pos,ref,alt,n_study,study,p_value,scz_af,hc_af,odds_ratio,se,info,qp,i_squared,mhtp,comment
0,8,105231413,T,C,2,+?,0.7843,0.9590,0.9600,1.01217,0.0442,0.999,1.0000,0.0,.,.
1,8,106973048,A,G,2,+-,0.4240,0.0713,0.0743,0.98531,0.0185,0.990,0.1990,-81.9,.,.
2,8,101592213,T,C,2,?-,0.3851,0.0716,0.0750,0.98167,0.0213,0.956,1.0000,0.0,.,.
3,8,102569817,A,G,2,-?,0.6736,0.0657,0.0662,0.98383,0.0387,0.885,1.0000,0.0,.,.
4,8,108690829,T,G,2,++,0.5957,0.4930,0.4940,1.00511,0.0095,0.982,0.9635,0.0,.,.

In [110]:
import requests
import ast

def get_query(gene_name):
    query = '''{
        gene(gene_name: "%s") {
          gene_name
          chrom
          transcript {
            exons {
              feature_type
              start
              stop
              strand
            }
          }
      }
    }''' % gene_name

    return query

def get_gene_intervals(gene_name, url='http://gnomad-api.broadinstitute.org/'):
    query = get_query(gene_name)
    headers = { "content-type": "application/graphql" }
    response = requests.post(url, data=query, headers=headers)
    parsed = ast.literal_eval(response.text)
    features = parsed['data']['gene']['transcript']['exons']
    chrom = parsed['data']['gene']['chrom']
    exons = filter(lambda feature: feature['feature_type'] == 'CDS', features)
    #intervals = map(lambda exon: '%s:%s-%s' % (chrom, exon['start'], exon['stop']), exons)
    bounds = (exons[0]['start'], exons[-1]['stop'])
    return bounds

if __name__ == '__main__':
    print(get_gene_intervals('BRCA2'))

(32890599, 32972905)

In [130]:
# -*- coding: utf-8 -*-
import pandas as pd
import json
from pymongo import MongoClient

settings = {
        'mongo_host': 'localhost',
        'mongo_db_name': 'exac',
        'mongo_port': 27017,
        'chunk_size': 100000,
        'drop_collections_on_load': True,
        'collection': 'schizophrenia',
        'file': '/Users/msolomon/Data/schizophrenia/daner_combined_refmt_change_headers.csv'
    }

def rename_columns(df):
    column_map = {
        '#CHR': 'chr',
        'BP': 'pos',
        'REF': 'ref',
        'ALT': 'alt',
        'nStudy': 'n_study',
        'Study': 'study',
        'P': 'p_value',
        'SCZ_AF': 'scz_af',
        'HC_AF': 'hc_af',
        'OR': 'odds_ratio',
        'SE': 'se',
        'Qp': 'qp',
        'I2': 'i_squared',
        'MHT.P': 'mhtp',
        'Comment': 'comment',
        'INFO': 'info'
    }
    return df.rename(columns=column_map)

def to_mongo(dest, data, idxs=[]):
    if (settings['drop_collections_on_load']):
        dest.drop()
    for chunk in data:
        dest.insert_many(json.loads(chunk.to_json(orient='records')))
    for idx in idxs:
        dest.ensure_index(idx)
        
if __name__ == "__main__":
    # establish connection:
    mongo_client = MongoClient(settings['mongo_host'],
                               settings['mongo_port'])
    mongo_db = mongo_client[settings['mongo_db_name']]

    # load data:
    data = pd.read_csv(
        settings['file'],
        # compression='gzip',
        chunksize=settings['chunk_size'],
        delimiter=',')

    # insert data:
    to_mongo(mongo_db[settings['collection']],
             data,
             ['pos'])

    # close connection:
    mongo_client.close()

/Users/msolomon/bin/miniconda3/envs/portal/lib/python2.7/site-packages/ipykernel_launcher.py:43: DeprecationWarning: ensure_index is deprecated. Use create_index instead.

In [127]:
prepared_df.to_csv('/Users/msolomon/Data/schizophrenia/daner_combined_refmt_change_headers.csv')